#!/usr/bin/python
import numpy as np


"""
functions for different features
and one function that brings them all together
"""

def number_of_black_pixels(col):
    """
    input: column of a image
    output: number of black pixels in this column
    """
    feature = np.sum(col>0)
    return feature

def upper_boundary(col)
    """
    input: column of a image
    output: minimal distance form upper boundary of the image to a black pixel in this column
    """

    return feature

def lower_boundary(col)
    """
    input: column of a image
    output: minimal distance form upper boundary of the image to the first black pixel in this column 
    """

    return feature

def black_white_transitions(col):
    """
    input: column of a image
    outbut: number of black and white transitions
    """

    return feature





def feature_extraction(col):
    """
    input: column of a image
    output: feature vector containing the different feature values of this column
    """

    return feature_vector